services:
  parquimetro-api:
    image: 'parquimetro-api:latest'
    build:
      context: .
    container_name: parquimetro-api
    depends_on:
      - postgres-db
    environment:
      - POSTGRES_USER=${USER_DB}
      - POSTGRES_PASSWORD=${PASSWORD_DB}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/parquimetro
      - SPRING_DATASOURCE_USERNAME=${USER_DB}
      - SPRING_DATASOURCE_PASSWORD=${PASSWORD_DB}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - parquimetro-api-network

  postgres-db:
    image: postgres:16.3
    container_name: postgres-db
    volumes:
      - ./scripts-db/01-create-schema.sql:/docker-entrypoint-initdb.d/01-create-schema.sql
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${USER_DB}
      - POSTGRES_PASSWORD=${PASSWORD_DB}
      - POSTGRES_DB=parquimetro
    networks:
      - parquimetro-api-network
    env_file:
      - .env
volumes:
  pgdata:

networks:
  parquimetro-api-network:
    driver: bridge
